# Generated by Django 5.1.2 on 2025-04-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_task_rejection_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
