# Generated by Django 5.1.2 on 2025-04-27 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_alter_task_status_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_requests', to='Backend.employee'),
        ),
    ]
