services:
  - type: web
    name: mobile-api
    env: docker
    region: oregon
    plan: starter
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: hrms-db
          property: connectionString
      - key: JWT_SECRET
        sync: false

databases:
  - name: hrms-db
    databaseName: hrms
    user: postgres